// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/4/2024, 10:32:39 AM
const configMerger = require("/home/roy/Projects/reproduction/reproduction/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/roy/Projects/reproduction/reproduction/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/roy/Projects/reproduction/reproduction/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/roy/Projects/reproduction/reproduction/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/roy/Projects/reproduction/reproduction/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/roy/Projects/reproduction/reproduction/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/roy/Projects/reproduction/reproduction/plugins/**/*.{js,ts,mjs}","/home/roy/Projects/reproduction/reproduction/composables/**/*.{js,ts,mjs}","/home/roy/Projects/reproduction/reproduction/utils/**/*.{js,ts,mjs}","/home/roy/Projects/reproduction/reproduction/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/roy/Projects/reproduction/reproduction/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/roy/Projects/reproduction/reproduction/app.config.{js,ts,mjs}"] }));

module.exports = config
